apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: test-workflow
  labels:
    app.kubernetes.io/name: test-workflow
    app.kubernetes.io/part-of: test-workflow-project
    kubernetes.azure.com/generator: devhub
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: test-workflow